return {
  {
    "sindrets/diffview.nvim",
    dependencies = "nvim-lua/plenary.nvim",
    cmd = { "DiffviewOpen", "DiffviewFileHistory" },
    keys = {
      { "<leader>gd", "<cmd>DiffviewOpen<cr>", desc = "Open Diffview" },
      { "<leader>gh", "<cmd>DiffviewFileHistory %<cr>", desc = "File History" },
      { "<leader>gH", "<cmd>DiffviewFileHistory<cr>", desc = "Branch History" },
    },
    opts = {
      diff_binaries = false,
      enhanced_diff_hl = true,
      use_icons = true,
      signs = {
        fold_closed = "",
        fold_open = "",
        done = "✓",
      },
      view = {
        default = {
          layout = "diff2_vertical",
          winbar_info = true,
        },
        merge_tool = {
          layout = "diff3_horizontal",  
          disable_diagnostics = true,
          winbar_info = true,
        },
        file_history = {
          layout = "diff2_vertical",
          winbar_info = true,
        },
      },
      file_panel = {
        listing_style = "tree",
        tree_options = {
          flatten_dirs = true,
          folder_statuses = "only_folded",
        },
        win_config = {
          position = "left",
          width = 35,
          win_opts = {},
        },
      },
      file_history_panel = {
        log_options = {
          git = {
            single_file = {
              diff_merges = "combined",
            },
            multi_file = {
              diff_merges = "first-parent",
            },
          },
        },
        win_config = {
          position = "bottom",
          height = 10,
        },
      },
      commit_log_panel = {
        win_config = {},
      },
      default_args = {
        DiffviewOpen = {},
        DiffviewFileHistory = {},
      },
      hooks = {},
      keymaps = {
        disable_defaults = false,
        view = {
          { "n", "<tab>", false },
          { "n", "<s-tab>", false },
          { "n", "]f", "<cmd>DiffviewFocusFile next<cr>", { desc = "Next file" } },
          { "n", "[f", "<cmd>DiffviewFocusFile prev<cr>", { desc = "Previous file" } },
        },
        file_panel = {
          { "n", "j", false },
          { "n", "k", false },
          { "n", "<cr>", false },
          { "n", "o", false },
          { "n", "<tab>", false },
          { "n", "<s-tab>", false },
          { "n", "gf", false },
          { "n", "<C-w><C-f>", false },
          { "n", "<C-w>gf", false },
          { "n", "i", false },
          { "n", "cc", false },
          { "n", "ca", false },
          { "n", "cu", false },
          { "n", "cU", false },
          { "n", "cr", false },
          { "n", "cR", false },
          { "n", "cx", false },
          { "n", "cX", false },
          { "n", "cp", false },
          { "n", "cP", false },
          { "n", "co", false },
          { "n", "R", false },
          { "n", "-", false },
          { "n", "s", false },
          { "n", "S", false },
          { "n", "U", false },
          { "n", "X", false },
          { "n", "]x", false },
          { "n", "[x", false },
          { "n", "L", false },
          { "n", "q", "<cmd>DiffviewClose<cr><cmd>qa<cr>", { desc = "Close Diffview and quit" } },
        },
        file_history_panel = {
          { "n", "g!", false },
          { "n", "<C-A-d>", false },
          { "n", "d", false },
          { "n", "<C-c>c", false },
          { "n", "L", false },
          { "n", "zo", false },
          { "n", "zc", false },
          { "n", "za", false },
          { "n", "zC", false },
          { "n", "zM", false },
          { "n", "zO", false },
          { "n", "zR", false },
          { "n", "j", false },
          { "n", "k", false },
          { "n", "<cr>", false },
          { "n", "o", false },
          { "n", "<tab>", false },
          { "n", "<s-tab>", false },
          { "n", "gf", false },
          { "n", "<C-w><C-f>", false },
          { "n", "<C-w>gf", false },
          { "n", "<C-c>o", false },
          { "n", "y", false },
          { "n", "q", "<cmd>DiffviewClose<cr><cmd>qa<cr>", { desc = "Close Diffview and quit" } },
        },
        option_panel = {
          { "n", "q", false },
        },
        help_panel = {
          { "n", "q", false },
        },
      },
    },
  },
}